version: '2'
services:

    hellowork-api:
        image: italolelis/hellowork:web
        environment:
            PORT: "8080"
            LOG_LEVEL: "debug"
            DATABASE_WRITE_DSN: "mongodb://mongodb/hellowork_work?sslmode=disable"
            DATABASE_READ_DSN: "mongodb://mongodb/hellowork_read?sslmode=disable"

    mongodb:
         image: mongo
         ports:
             - "27017:27017"
